### ISSUE TITLE
Audioswitch is not starting

### ISSUE THREAD

**Issue by Newbiez** [sirWest/AudioSwitch#1]
Did a update to RC 6, because Audioswitch was not starting anymore here on Win 8.1.
But same error as before seen in event manager, with log output from log file now.

Log Entry: 09.05.2015 17:24:54

System.InvalidOperationException: Fehler im XML-Dokument (0,0). ---> System.Xml.XmlException: Das Stammelement ist nicht vorhanden.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlTextReader.Read()
   bei System.Xml.XmlReader.MoveToContent()
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read12_Settings()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   bei System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   bei AudioSwitch.Classes.Settings.Load()
   bei AudioSwitch.Classes.Program.Main(String[] args)

**Comment by sirWest** [comment]
Did you delete the old Settings.xml file before installing the new version? There seems to be a problem where the settings file gets corrupted in some unknown cases and gets written as an empty file. I'm looking into it and trying to move the saving to somewhere more safe but until that happens the only way is to delete the file and reinstall AudioSwitch. I'm really sorry that it still causes problems for you :(

**Comment by Newbiez** [comment]
The problem i have updated because it was not starting anymore...
I checked the settings file now. It was empty! Last change 29.4.15. 10 Days before update. 
I was a little bit lazy and replaced the exe only. So the empty settings file was not replaced. My fault.

I copied also the delivered settings file and Audioswitch is working again.
Thank you for your support.
