### ISSUE TITLE
[Request] Ubuntu/Linux support?

### ISSUE THREAD

**Issue by Snowman3456** [sirWest/AudioSwitch#100]
Pretty awesome utility. Wish I could use it in Linux.

**Comment by n1trux** [comment]
You can just use PulseAudio ([pavucontrol](https://duckduckgo.com/?q=pavucontrol&ia=web)). This tool would not work at all since it's written with the CoreAudio API which is only available for Windows.

**Comment by Snowman3456** [comment]
A taskbar based utility is ideal. Opening an application like `pavucontrol` is the same as opening windows `playback devices` which nullifies the purpose of this app. It's square one.

In GNOME however, there are some GNOME Extensions which more or less do what this utility brings to the table. https://extensions.gnome.org/extension/1092/audio-switcher/

It's built into the taskbar system menu so still one layer deeper than this but solves my problem.
