### ISSUE TITLE
setup parameters

### ISSUE THREAD

**Issue by gsnijders** [sirWest/AudioSwitch#101]
Love the tool and I'd like to deploy it to a number of computers.

Would it be possible to disable the donate page when using the /verysilent setup parameter?
The "verysilent " option is really useful when deploying software to any number of PC's, but right now the donate page is always opened. That can be bit confusing to users (who are not always aware that I updated an application ;) ).

**Comment by sirWest** [comment]
done, that was easy :)

**Comment by sirWest** [comment]
I'm not sure that I can change it but I will look into Inno Setup options
and I'll answer back here what I find
