### ISSUE TITLE
Error when opening settings on windows 10 64bit

### ISSUE THREAD

**Issue by ishalem** [sirWest/AudioSwitch#106]
failing on this line 
 icon = Icon.FromHandle(hIconEx[0]);

![image](https://cloud.githubusercontent.com/assets/3824532/20308173/5cd82ea4-ab4b-11e6-8322-992e42218800.png)

**Comment by alensiljak** [comment]
... when right-clicking the tray icon.

**Comment by alensiljak** [comment]
OK, as it seems that there are no reactions for a long time, I have corrected this issue in a forked branch:

https://github.com/MisterY/AudioSwitch/releases/tag/2.2.0.0

**Comment by sirWest** [comment]
Fixed in latest version
