### ISSUE TITLE
hot keys dont work

### ISSUE THREAD

**Issue by ghost** [sirWest/AudioSwitch#112]
some hotkeys just dont work. i would also like to see custom keys like on my keyboard i have "g" keys that i dont use, i would love to use them for this.

**Comment by tryallthethings** [comment]
Do you mean the G-Keys of Logitech Keyboards? You can't bind those directly since they only emulate other Keyboard presses. But you can assign a hotkey to a function and record it on a G-Key. Then you can execute rather complicated hotkeys with the press of a single button.

**Comment by ghost** [comment]
Wow, your right. I don't know how I just flew over this. Thank you :)
