### ISSUE TITLE
Device OSD

### ISSUE THREAD

**Issue by atlraider** [sirWest/AudioSwitch#115]
This program works great for me. Thanks! The only thing I am missing is an OSD or notification showing what device I have toggled to when cycling through playback devices via hotkeys. Just a feature request for consideration. Thanks again for solving what was once a big problem with Windows 10!

**Comment by fwmurnau** [comment]
I totally agree with this request. I've been using the 2.0 version of Audioswitch until recently when it suddenly crashed right after logon (dunno why- I've got Win 7 installed). So I've started using the latest version instead and the thing I miss most is the above mentioned notification or OSD that appeared everytime I switched playback deviced via hotkeys. I'd strongly recommend bringing this feature back (you could make it optional, though... I suppose it might annoy some people).

**Comment by fwmurnau** [comment]
Oh and of course, I love the app itself :-) Sorry, didn't want to sound too critical in my previous post :-D
I remember when I first came across Audioswitch... I thought 'well this must be one of the best unofficial extensions for Windows ever' (right next to the one that enables tabbed browsing multiple documents in Microsoft Office :D :D )"

**Comment by sirWest** [comment]
It exists already, tick the OSD option in hotkey row
