### ISSUE TITLE
Taskbar/Tray menu listbox is not sized correctly

### ISSUE THREAD

**Issue by ghost** [sirWest/AudioSwitch#117]
Since I installed an RME HSDPe card with tons of I/O, the listbox in the tray menu is not much shorter than the menu window itself. I have a short Listbox on top, an almost as much grey space below that, and then, at the bottom, the peak meter. This happens for both the input device selection and the output device selection.

![2017-04-27 16_50_19-](https://cloud.githubusercontent.com/assets/12282673/25491039/06286336-2b6f-11e7-90d9-477bfadcc5d2.png)

**Comment by sirWest** [comment]
This looks like black magic. Can you try the latest version and report back?

**Comment by sirWest** [comment]
Try the latest version and report back the results

**Comment by ghost** [comment]
I am happy to say this is fixed some time beetween June and 2.2.2! Kudos!
![image](https://user-images.githubusercontent.com/12282673/35081857-bd946150-fc16-11e7-80de-b21a03c42ef0.png)
