### ISSUE TITLE
[Suggestion] Movable onclick window

### ISSUE THREAD

**Issue by xMez** [sirWest/AudioSwitch#120]
The onclick window appears in the middle of my two monitors, it would be great if it was possible to set it manually as I would want it in the bottom right but still have the taskbar ontop.

**Comment by mintgrey** [comment]
Hi,

I want to add my support to this suggestion :)

Actually, it would be great if you can show the selector in two different modes, that can be configured in the settings tab :
- 1 mode where the selector is wrap in a task menu (like today) that popups when you click on the task bar icon, but that disappears when you clicks somewhere else :(
- 1 mode where the selector is wrap in a standard window (with the same dimensions than the standard task menu) that popups when you click on the task bar icon, but that *leaves always open* until you manually want to close it by clicking on the standard X button.

In fact for my usage, i have 2 screens : I like to keep some "dashboard" settings on my second screen, like a hardware monitor (temp, cpu usage, ...) and some Windows key-settings, like the possibility to see and switch my default sound output between my standard speakers, my headset or my spdif output to hi-fi.

Thank you for the consideration of this suggestion

**Comment by sirWest** [comment]
it was a very nice feature idea, go try it out ;)
