### ISSUE TITLE
Pop Window on Left Click appears offscreen at 1920x1080 (Windows 8.1, laptop)

### ISSUE THREAD

**Issue by manwithacat** [sirWest/AudioSwitch#15]
On Windows 8.1, clicking on the tray icon opens the popup window, but it appears mostly offscreen. The top of the window appears to be level with the midpoint of the taskbar.

Only happens at 1920x1080 on my laptop [Intel Integrated Graphics + Nvidia]. Works fine at 1920x1080 resolution on a desktop screen, and works fine at any lower resolution on the laptop too.

All the hotkeys and functions work fine. OSD is all good. Just the pop-up window that's misplaced.

(Tried a few quick things like Windows 7 compatibility mode, forcing the program to use the Intel Integrated Graphics, running as administrator. Only thing that gets the window to display as expected is lowering the resolution)

**Comment by sirWest** [comment]
do you have a higher than normal DPI setting applied? This could also affect it's workings, although I thought that at least the positioning got fixed. Nothing else shouldn't do this I think. Can you please see what's your DPI scaling where it happens?

**Comment by manwithacat** [comment]
Aha. At 1080p60, if I set the option "Make text and other items Larger or Smaller"
to "small", then Audioswitcher is fine. Using the middle (unlabeled/medium) or
large settings the popup appears off-screen.

**Comment by kev007** [comment]
Try:
AudioSwitch.exe -> Right Click -> Properties -> Compatibility-> ☑ Disable display scaling on high DPI settings

**Comment by manwithacat** [comment]
Brilliant. That sorts it out.
