### ISSUE TITLE
Windows 10 start error

### ISSUE THREAD

**Issue by Andy2244** [sirWest/AudioSwitch#16]
Hi,

out of curiosity i tried to run AudioSwitch 2.01 on the Windows 10 preview build 10166 and get this error:

System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at AudioSwitch.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(EDataFlow dataFlow, ERole role)
   at AudioSwitch.Controls.VolumeBar.RegisterDevice(EDataFlow RenderType)
   at AudioSwitch.Forms.FormSwitcher..ctor()
   at AudioSwitch.Classes.Program.Main(String[] args)

I tried using the Windows 7 compatibility option, but same result. Windows 10 comes with .Net 4.6 installed so maybe you can take a look at some point. I assume i'm not the only one that will make use of the 1 year "free" upgrade option.

thx
Andy

PS: I had hopes that Win10 would come with a better Audio Device switch system, but seems we still need AudioSwitch to-do the job. Win 10 is also supposed to-be the "last Windows Version" so hopefully a adapted/compatible Win10 version would be much longer compatible.

**Comment by sirWest** [comment]
actually I'm running it daily also on Windows 10 (build 10162) and it's working for me. Don't try any compatibility modes, this might just confuse things more. So they probably either fixed some stuff back that they had changed and I did some workarounds for, or there are some totally new changes again. I'll see and test this myself when I get a newer build. Until that, stay tuned, I'll let you know in this issue ticket of any changes or progress.

**Comment by Andy2244** [comment]
Oh lol, my bad i was on my test machine via a RDP session and had not enabled audio services on the remote machine. Just retested locally and works fine :p
