### ISSUE TITLE
AudioSwitch crashes when adjusting volume with foobar

### ISSUE THREAD

**Issue by kekx** [sirWest/AudioSwitch#2]
I had this problem with some old version and it still persists with 2.0 RC6.
Lets say I have foobar playing a song and AudioSwitch running. Everything works fine.
But as soon as I click on the volume bar in foobar, AudioSwitch crashes instantly.
Same happens when I adjust the volume in the Windows volume mixer:
http://push2.anukthewolf.com/a/2015-05-10_11-46-06.png
I assume AudioSwitch doesn't like individual app volume changes.

**Comment by kekx** [comment]
Seems to work after a PC restart, let's see how long..

**Comment by kekx** [comment]
Nope, still happens sometimes

**Comment by SigHunter** [comment]
seems gone in RC7

**Comment by SigHunter** [comment]
nope, still happens with RC7

**Comment by sirWest** [comment]
Can you please tell me both what Windows versions are you using, also, is it happening regardless of what is currently playing the audio (chrome, foobar, firefox, iTunes etc) or it happens always? First of all I'd like to get some information about what you both might have in common. This doesn't happen to me and I can adjust all the volumes separately from the mixer and also from different music players. I'd very much like to get to the bottom of this with your help. Thank you guys for your reports!

**Comment by kekx** [comment]
Okay, I'm using Windows 8.1 64-bit.
I just tested what you asked for and the problem only seems to come up when adjusting foobar's volume in Audioswitch itself, in foobar or in the Windows audio mixer, no matter if there's a song playing in foobar or not. If I start a video in Chrome and adjust the volume in the volume mixer, everything works as expected.

//Okay, I investigated some more:
Usually I'm using a S/PDIF Pass-through output of my sound card.
I get the following results if I change the output in foobar/AudioSwitch to the following and change the volume afterwards (in foobar or windows audio mixer, in AS it works as it should):
1. Foobar: Speaker, AS: Speaker -> No crash
2. Foobar: Speaker, AS: S/PDIF pass-through -> No crash (still get sound due to my soundcard redirecting it to S/PDIF out, but that's not an issue)
3. Foobar: S/PDIF pass-through, AS: Speaker -> No crash (still sound)
4. Foobar: S/PDIF pass-through, AS: S/PDIF pass-through -> Crash!

So I guess AudioSwitch doesn't like that I change a digital pass-through output's volume via any volume switch other than AS's one. Maybe the issue is just the "sync" between AS's volume level and other volume levels on pass-through devices?

**Comment by sirWest** [comment]
ughh this is now weird. I just installed foobar for that purpose, to test it, and on my Windows 10 build 10130 it works. I have Win 8.1 x64 at work, I will do the same test on Monday when I get there. This now really puzzles me, I can change the volume from where I want to either during playing or while stopped, no issues at all.

**Comment by kekx** [comment]
As I have said, this only seems to happen on pass-through outputs, so it's hard to test if you don't have one.

One more test:
5. Foobar: Default Audio Device (thus same as AS); AS: S/PDIF pass-through -> Still crash.
Thought that might make a difference but it doesn't

//EDIT:
Okay after a restart of foobar, 5) seems to work. So AS just doesn't seem to like that I put both foobar's output and the desired output device (via AS) explicitly on Pass-Through.
I'll test that one a few more times and report if it changes.

//EDIT 2:
Nope, sometimes 5) works and sometimes it doesn't. It's really weird.

I can't even debug AS via Visual Studio because when I trigger that bug and click on Debug, the old settings still are in the debugged process and it crashes as well. So I can't help you with that..

**Comment by sirWest** [comment]
search for "SafeSet(newVolume, newMute);" in the solution and put a breakpoint on that. Look what are the values that are coming in or try to step in with F11 and see what's happening. I don't have digital audio on either of my PC's, only on HTPC computer but currently I don't see any remotely sane way to debug AS there. If you can't get anywhere with this then I probably have to look into some remote debugging...

**Comment by kekx** [comment]
Okay, so I just set a breakpoint in there and it successfully stopped as soon as I changed the volume in foobar. 
Here is a screenshot of the values:
http://push.anukthewolf.com/a/2015-05-31_17-02-20.png

I also stepped through the method and saw that it invokes the "newMethodWithFloatArg" (but couldn't step in there as well), then went out of SafeSet, returned 0 and crashed after all that.

I could let you control my PC via Anydesk so you can debug it yourself. That would be the easiest thing to do, I guess

**Comment by SigHunter** [comment]
Hi guys,

sorry for the late response.

I tried to investigate the problem but unfortunately I couldn't recreate it anymore.
Maybe because just yesterday I switched to Win10 build 10130.

I use S/PDIF aswell as HDMI for playback. After update to 10130 I 
had to set the output bitrate from 24 to 16 to get sound working. 
Could this be responsible for this problem? 
Unfortunately I'm no programmer, so can't help with breakpoints 'n' stuff.

Regards

**Comment by kekx** [comment]
Hey SigHunter,
thanks for the tip, I just changed my bitrate to 16 and since then it works without a problem, even if I put it back to 24 bit.. I'll restart my pc and report if anything stops working

**Comment by kekx** [comment]
I think I made a bit of progress with this:
Did some program starting/stopping and changing bitrates and wrote down each step, this way I could replicate the crash almost everytime:

Initial situation: 24bit, foobar stopped, AS stopped

start foobar -> start AS -(still works)> set to 16bit -(still works)
start foobar -> start AS -(still works)> stop AS -> set to 16bit -> start AS -(still works)

set to 16bit -> start foobar -> start AS --> Crash -> set to 24bit -> start AS --> Crash -> restart foobar -> start AS -> no crash anymore

set to 16bit -> start wmp   -> start AS --> Crash -> set to 24bit -> start AS --> Crash -> restart wmp    -> start AS -> no crash anymore

It seems a bit weird but both of the players seem to do something if there is a new bitrate set that wasnt set when they've been run the last time. And AS probably just can't handle that. But that still doesn't explain why it happens on every computer restart when the bitrate should be set to a known value.

I'd love to upgrade to Windows 10 as well, but my anti virus program doesn't support it yet :/ I guess I'll try to install it in a virtual machine and try to replicate the crash there, even if that might not be very conclusive.

**Comment by sirWest** [comment]
I installed foobar on my HTPC together with Visual Studio 2013 remote debugging tools and I can replicate the crash when changing the separate volume of that stream which goes to digital output. I managed to trace it to the audioses.dll where it crashes on the line:
AudioSes.dll!CLockedListATL::CComPtr<IAudioSessionEvents,0,1>::ForEachEntry()
I investigated it and it seems it's a problem with threading on the software that listens to the events (AudioSwitch). There doesn't seem to be any answers around it anywhere, so currently I don't see any other option than to either ignore the problem or rework a huge part of AS into C++ code where this threading is done manually, which is 1000 times more difficult but supposedly it would work. Not sure that I like either of these options. We would need some advice by someone who has deep knowledge of CoreAudioAPI and AudioSessions.

**Comment by kekx** [comment]
Ah okay, nice to know that you found the source of the problem. As it seems to work with Windows 10, I'll try to live with the problem until Win 10 is out or update to the Insider preview.
If no one knows an answer to this, I'd just wait because the effort is not worth it for just two people having the problem^^

**Comment by sirWest** [comment]
I just uploaded the new RC8, try that. I found the problem - for some strange legacy reasons I also assigned to the base session for volume notifications, this is actually not necessary since I also assign to the master volume of the MMDevice anyway, I don't need those changes from sessions at all (facepalm). Since I was able to remove also a lot of code then I won't commit the code before I get at least one +1 for solving it and that it works any other way also as expected, no glitches. For me it seems to work perfectly, so I'm really positive about this :) Waiting for your feedback!

**Comment by kekx** [comment]
Oh that sounds great, thanks for your efforts!
Just installed it and had some problems getting it to run because some settings.xml hotkey entries had invalid values. After deleting those it seems to work pretty nice, I had no luck reproducing the problem so far, even with the ways I found before.

Here's the log. These entries basically say that "SwitchPlaybackDevice" is not a valid value for HotkeyFunction. After the first launch I deleted that line and then it obviously said that "SwitchRecordingDevice" isnt one either. After that I deleted all of them xD

Log Entry: 03.06.2015 20:41:45

System.InvalidOperationException: Fehler im XML-Dokument (9,11). ---> System.InvalidOperationException: Instanzvalidierungsfehler: 'SwitchPlaybackDevice' ist kein gültiger Wert für HotkeyFunction.
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read6_HotkeyFunction(String s)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read9_Hotkey(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read11_Settings(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read12_Settings()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   bei System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   bei AudioSwitch.Classes.Settings.Load()
   bei AudioSwitch.Classes.Program.Main(String[] args)

Log Entry: 03.06.2015 20:43:42

System.InvalidOperationException: Fehler im XML-Dokument (9,11). ---> System.InvalidOperationException: Instanzvalidierungsfehler: 'SwitchRecordingDevice' ist kein gültiger Wert für HotkeyFunction.
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read6_HotkeyFunction(String s)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read9_Hotkey(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read11_Settings(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read12_Settings()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   bei System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   bei AudioSwitch.Classes.Settings.Load()
   bei AudioSwitch.Classes.Program.Main(String[] args)

**Comment by SigHunter** [comment]
Same here, crashed, then I deleted the whole %appdata%\Audioswitch (or was it %localappdata%, can't remember :D) and it started. so far no crash, thanks

**Comment by sirWest** [comment]
ohhh yea I added one requested feature there where you can select either next or previous device with a hotkey and I also changed the function names... I should start using some migration code for these things, I'm sloppy :( But great to hear that it works otherwise :)
