### ISSUE TITLE
Sometimes GUI elements desapear

### ISSUE THREAD

**Issue by bolaum** [sirWest/AudioSwitch#21]
Randomly, all GUI elements desapear and they don't come back even after I restart the app. The weird thing is that all elements (list of devices, sliders, context menu) still work, I just can't see what I'm clicking on.

Edit: Windows 7 64

![guiproblem](https://cloud.githubusercontent.com/assets/1623498/9021914/3602dfd0-3834-11e5-82ed-5552b9f5d82e.png)

![guiproblem2](https://cloud.githubusercontent.com/assets/1623498/9021915/382b0616-3834-11e5-99a9-5a7b51817471.png)

**Comment by sirWest** [comment]
this is the most magical bug to date :+1: 
I'll need some more info on that, if you're using any windows UI customization, like custom themes with modified uxtheme etc

**Comment by bolaum** [comment]
Nevermind. This is probably a problem with my system since It's happening with other apps.

Thanks!
