### ISSUE TITLE
can't write to setting.xml

### ISSUE THREAD

**Issue by Andyriod** [sirWest/AudioSwitch#23]
Every Time when I shutdown the computer a error occures, telling me AudioSwitch can't write to Program Files/AudioSwitch/Settings.xml.
Should you change the Path of Settings.xml to %AppData% ?

**Comment by sirWest** [comment]
it's actually meant to be installed in appdata folder by default by the setup and then it's used from it's own folder. You can either reinstall or move it to appdata or give writing rights to the AudioSwitch folder in program files.
