### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by ghost** [sirWest/AudioSwitch#25]
This seems like a good compromise to windows limitations, but compiling code is well above my head. Any chance of a binary?

**Comment by kev007** [comment]
There is a link ["AudioSwitch latest setups"](https://drive.google.com/folderview?id=0B8VyHhqTufh1fkVlRElYZXlxRlJlUGtwX2tIYXM5VDlwXzl5MDJUQ1loelM3QmxRUlJsN0k&usp=sharing) on the repo page linking to the latest binaries.

**Comment by ghost** [comment]
Thank you, I have no idea how I didn't see that :/
