### ISSUE TITLE
Crash when Alt+F4

### ISSUE THREAD

**Issue by joancifo** [sirWest/AudioSwitch#26]
Hello! I love you app! 

I detected a minor bug: When AudioSwitch has focus if Alt+F4 is pressed it crashes with next error (sorry, I have my system in spanish).

I have Windows 10 but it also happened with Windows 7 (64 bits).

Thank you!

Error:

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

*************\* Texto de la excepción **************
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en System.Windows.Forms.NotifyIcon.UpdateIcon(Boolean showIconInTray)
   en System.Windows.Forms.NotifyIcon.set_Icon(Icon value)
   en AudioSwitch.Forms.FormSwitcher.IconChanged(Object sender, EventArgs eventArgs)
   en AudioSwitch.Controls.VolumeBar.set_Value(Single value)
   en AudioSwitch.Controls.VolumeBar.RegisterDevice(EDataFlow RenderType)
   en AudioSwitch.Forms.FormSwitcher.FormSwitcher_Deactivate(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnDeactivate(EventArgs e)
   en System.Windows.Forms.Form.set_Active(Boolean value)
   en System.Windows.Forms.Form.WmActivate(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en AudioSwitch.Forms.FormSwitcher.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.96.0 built by: NETFXREL2STAGE
##     Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

AudioSwitch
    Versión del ensamblado: 2.1.1.0
    Versión Win32: 2.1.1
##     Código base: file:///C:/Users/User/AppData/Local/AudioSwitch/AudioSwitch.exe

System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll

System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.6.79.0 built by: NETFXREL2
##     Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by sirWest** [comment]
fixed in 2.1.3
