### ISSUE TITLE
Hotkey Next Playback Device still cycles through hidden output devices

### ISSUE THREAD

**Issue by djak250** [sirWest/AudioSwitch#29]
This is just a feature request I guess, but could we have the hotkey setup for nextPlaybackDevice honor the settings that we set to hide certain devices. Currently I have to cycle through all of them, even though I use two of them, and have hidden the others from the menu.

**Comment by djak250** [comment]
I actually wouldn't mind trying out a fix on my own for this. Not much experience with C#, but it doesn't look too hard to figure it out from reading through your code.

**Comment by namelessrabbit** [comment]
Yep, that would be handy. I'd be glad to see someone with coding skills helping out here :-)

**Comment by sirWest** [comment]
fixed in latest version :)
