### ISSUE TITLE
Option for OSD position on screen

### ISSUE THREAD

**Issue by hansek** [sirWest/AudioSwitch#3]
It would be nice to have an option to be able set position where should OSD appear.

TL - TC - TR
ML - MC - MR
BL - BC - BR

Top
Center
Right
Middle
Bottom

**Comment by sirWest** [comment]
Open settings and when the last tab is selected the OSD becomes visible.
You can drag it and it remembers it's position.

**Comment by hansek** [comment]
:+1: Nice! Thanks for your reply.

In this case, it would be nice to have some "hint" on General tab, to everyone know about this feature ;)

It's a bit hidden :)

Btw. same is the functionality in Hotkeys tab, because I couldn't find way how to disable all the hotkeys, after a while a found the way, I can select all rows by mouse and press DEL key. This should have definitely some information text as well. ;)

However great job with this app, looking forward to next updates! ;)
