### ISSUE TITLE
Bug with settings.xml

### ISSUE THREAD

**Issue by joelewis-phasealpha** [sirWest/AudioSwitch#38]
After installing on Windows 10, I was encountering an error that was causing AudioSwitch to immediately abend upon startup.  I downloaded the code to trace it and found I was missing the folder represented by the variable "Program.AppDataRoot".  I update the code on my end in the AudioSwitch.Classes.Settings.Save function to add the following code before instantiating the new StreamWriter: 

if (!Directory.Exists(Program.AppDataRoot))
{
    Directory.CreateDirectory(Program.AppDataRoot);
}

This created the folder for me and now I am in good shape.  I presume this was supposed to happen in the installer, but for some reason it did not.  I didn't observe it running as Administrator, so maybe it was a permission issue during install.  Not sure how you want to resolve this issue, but thought it might be helpful.

Cheers,

Joe Lewis
PhaseAlpha, LLC

**Comment by sirWest** [comment]
I actually re-uploaded the setup for creating that folder during the setup already, re-download it if needed. In the future I will shift this to code because in theory AudioSwitch should work also without setup.

**Comment by joelewis-phasealpha** [comment]
Appreciate you making this handy utility.  Thanks for your fast response!
