### ISSUE TITLE
Ability to select specific sound device or roll backwards

### ISSUE THREAD

**Issue by dayjobtitus** [sirWest/AudioSwitch#5]
Right now we can goto the next device but I would love to be able to go backwards and/or some command to select a specific one using your same program.

Use case:
I have a keyboard with macros and have set two buttons to use your switcher but they should be able to scroll forwards and back but instead both go forward for now. Would love to make this work and maybe include a fast switch button as well.

**Comment by sirWest** [comment]
It's easier for me to just implement a backwards selection right now, I've also thought about the device-specific shortcut idea myself for a long while now, it just needs a bit more complicated logic. I will try to get the backwards-next device selection to the next version (RC8).

**Comment by sirWest** [comment]
also you can use command-line mode of AudioSwitch where you can specify the device either by sequence number or by device name. Just open the command prompt in AudioSwitch folder and type AudioSwitch /help
