### ISSUE TITLE
All versions for download from Google Drive are listed as having a virus and barred from download except for the owner

### ISSUE THREAD

**Issue by mattaw** [sirWest/AudioSwitch#55]
Using the links from the bottom of the frontpage to try to download the program google blocks it with the message above.

Tried various older versions and got the same result.

Dr S

**Comment by bziemek** [comment]
I can second this issue. Google drive is prohibiting download on account of suspected virus infection.

Additionally, I would like to recommend using Github to distribute releases in the future. [It's nice and easy](https://help.github.com/articles/creating-releases/).

**Comment by sirWest** [comment]
@bziemek this was a helpful tip, thanks a lot :)
Now everyone get your version from releases tab!

**Comment by mattaw** [comment]
Bziemek, thanks!
SirWest double thanks for writing the util!

DrS
