### ISSUE TITLE
Can't open settings menu

### ISSUE THREAD

**Issue by rabbleroo** [sirWest/AudioSwitch#70]
After enabling an option to change right-clicking the audioswitch icon in the system tray to cycle through audio devices, I now have no way of opening the audioswitch settings menu. I've tried uninstalling and reinstalling audioswitch in order to set the settings to default, but it hasn't worked.

**Comment by sirWest** [comment]
Open AudioSwitch first and then right-click the icon, then you'll see the
menu like before
