### ISSUE TITLE
Unexpected Error during initial launch

### ISSUE THREAD

**Issue by pseudoid** [sirWest/AudioSwitch#8]
Install attempt is via Win8.1Pro 32Bit (fully updated)
Default Install Directory becomes "C:\Users\Nur Who\AppData\Local\AudioSwitch"
It does not matter if the Default Directory is changed to something other..
It does not matter if user selects to make program AutoStart or not.
It does not matter, whether the installation is attempted via Admin account or a regular User account w/Admin privileges.
Appears to uninstall properly upon the "Unexpected Error" dialogue!
# ![201506_unexpectederror1stlaunch](https://cloud.githubusercontent.com/assets/6992068/8047915/3a1263a6-0e00-11e5-88fd-02b6b66c645d.png)

Log Entry: 2015-06-08 08:40:26
System.IO.FileNotFoundException: C:\WINDOWS\system32\explorer.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at AudioSwitch.Forms.FormSwitcher..ctor()
##    at AudioSwitch.Classes.Program.Main(String[] args)

Log Entry: 2015-06-08 08:41:02
System.IO.FileNotFoundException: C:\WINDOWS\system32\explorer.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at AudioSwitch.Forms.FormSwitcher..ctor()
##    at AudioSwitch.Classes.Program.Main(String[] args)

Log Entry: 6/8/2015 4:35:58 PM
System.IO.FileNotFoundException: C:\WINDOWS\system32\explorer.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at AudioSwitch.Forms.FormSwitcher..ctor()
##    at AudioSwitch.Classes.Program.Main(String[] args)

Log Entry: 2015-06-08 16:41:38
System.IO.FileNotFoundException: C:\WINDOWS\system32\explorer.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at AudioSwitch.Forms.FormSwitcher..ctor()

**Comment by sirWest** [comment]
I see the problem, I'll try to get it fixed in a few hours.

**Comment by sirWest** [comment]
try the new RC13, it should fix this.

**Comment by pseudoid** [comment]
RC13 change worked! I may be wrong but the default install location
should NOT be the user directory. Win8.1 also complains that the
install will terminate since source is not verified >> but can be
overridden! Now you have to tell me what you changed to make it work,
in return as a favor!

----- Original message -----

**Comment by sirWest** [comment]
Well since the Settings.xml should be writable then it makes the most sense to install it to the user-specific directory, that's where Google Chrome for example is also installed. Keeping the app and settings in different locations would make even less sense.

I was mistakenly using a wrong environment path for finding the explorer.exe, it looked in the system folder not in windows folder. I'm using the version number from explorer.exe to detect if running Windows 10 or not :)
