### ISSUE TITLE
'Audio Switcher' Leaves a gap in my taskbar after a restart, anything I put there vanishes forever, and many other issues

### ISSUE THREAD

**Issue by All-github-usernames-taken** [sirWest/AudioSwitch#80]
Hi,

I have Audio Switcher installed, and it worked fine. However, when I restart my computer, it leaves a gap in my notification try area on my taskbar [issue.png]. Any other notification icon I put there vanishes forever and never comes back.

I have tried:

> Restarting explorer.exe
> Uninstalling the program
> Going into Windows settings to enable or disable notification icons for AudioSwitcher.exe [issue2.png]
> Anything else possible.
> Changing DPI Scaling
> Switching between Windows 10 and Windows 8 DPI Scaling Methods.

My resolution: 3840x2160, 60Hz, DPI Scaling 170%, Using this: http://bit.ly/1X310PD

These forums are completely empty and the dev is not responding at all. Is this some kind of joke?Where is the developer???

issue.png
![issue](https://cloud.githubusercontent.com/assets/20014057/16171206/fafd1844-3560-11e6-9f94-8b722c5d744d.PNG)

issue2.png
![issue2](https://cloud.githubusercontent.com/assets/20014057/16171207/fafe245a-3560-11e6-9b21-1d8060c86caa.png)

**Comment by sirWest** [comment]
Developer can't possibly imagine such black hole and closed the issue in horrible fear of doom
