### ISSUE TITLE
Settings not available

### ISSUE THREAD

**Issue by PavelA85** [sirWest/AudioSwitch#88]
Hi,
after changing settings to switch audio device with right mouse button, I cant find way to open settings.
Reinstall do not "forget" previous install settings.
How can I access settings?

**Comment by vdesmet93** [comment]
According to the settings "Right-clicking tray icon opens ... menu when AudioSwitch is open, otherwise quick-switches device".
So, just do a left-click to open the AudioSwitch UI, then do a right-click to access settings menu.

**Comment by PavelA85** [comment]
@vdesmet93 thanks for your reply
I made settings `quick-switches device` option
Now when I do right click I get device switch, left-click does nothing.

**Comment by danparsons** [comment]
I can confirm: On Windows 10 Anniversary Edition, with the above option enabled, there is no way to bring the settings UI up again. Right click switches devices, left click does nothing. I repeat: left clicking the tray icon in this mode does exactly nothing. I am completely locked out of settings now.

**Comment by vdesmet93** [comment]
Ok, I can't reproduce it  on my PC, and I'm not the developer so I don't know what causes the issue.
But you should try to edit the settings file manually.
It's located in `C:\Users\USERNAME\AppData\Local\AudioSwitch\Settings.xml`. Open the Settings.xml file in an editor, and change the value for `QuickSwitchEnabled` to `false`.

It will probably look like this
`<QuickSwitchEnabled>true</QuickSwitchEnabled>`

change it to:
`<QuickSwitchEnabled>false</QuickSwitchEnabled>`

Be sure to close the AudioSwitch app first(via Task Manager), then open the Settings.xml file, edit the file, save it and reopen AudioSwitch.

**Comment by PavelA85** [comment]
My issue "disappeared" after some time
