### ISSUE TITLE
[Suggestion] Allow renaming of devices

### ISSUE THREAD

**Issue by zim514** [sirWest/AudioSwitch#94]
Allow renaming of devices for users with multiple devices. When you have many devices, the device names can be confusing and not user friendly for some users in the house hold. Removing the device name can show multiple devices with the same name (Eg: Speakers). A custom label or name to replace the device name in the quick select menu would be helpful for these situations.

**Comment by vavido** [comment]
You can already rename Audio devices from the Control Panel audio devices menu. 
Right click on the device you want to rename, then go to properties. There you can set a different name and icon for the device.

**Comment by sirWest** [comment]
Added in latest version
